### PR TITLE
TER-77 repeated order by

### PR DESCRIPTION
**Pull request by martinjunger**
Jira: TER-77
driver-common: https://github.com/keboola/php-storage-driver-common/pull/19
connection: https://github.com/keboola/connection/pull/4097

Composer dev branches:
```
$ dcrr dev composer update keboola/storage-driver-common

        "keboola/storage-driver-common": "dev-TER-77-repeated-orderBy as 1.4.0",
```

### CODE REVIEW

**Comment by romanbracinik** [comment]
👁️

**Review by romanbracinik — COMMENTED** [review]
lgtm upravil by som este nejaky test aby sa testovalo orderBy podla viac stlpcov.

**Comment by martinjunger** [comment]
> lgtm upravil by som este nejaky test aby sa testovalo orderBy podla viac stlpcov.

Pridal jsem test pro vicenasobny OrderBy, jen ted padaji testy na policy limutu, tak to nemuzeme testnout a mergnout :-(

**Comment by romanbracinik** [comment]
```
1) Keboola\StorageDriver\FunctionalTests\UseCase\Table\PreviewTableTest::testPreviewTable
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'3'
+'4'

```
@martinjunger pada ti tam este jeden test , ten prvi error v testoch by sa uz nemal stat v tom dalsom rune. Skusim tam este pridat nejaky retry aby sa to nestavalo

**Comment by martinjunger** [comment]
> pada ti tam este jeden test , ten prvi error v testoch by sa uz nemal stat v tom dalsom rune. Skusim tam este pridat nejaky retry aby sa to nestavalo

Dik, test upravim. Pridaval jsem tam to razeni a nemel to jak zkusit, tak to je jen od oka :)

**Review by romanbracinik — APPROVED** [review]
lgtm tu to uz dobehlo zelene https://github.com/keboola/php-storage-driver-bigquery/actions/runs/3638999063

**Pull request merged**
